package com.task2;

public enum FieldMatching {
    FIELD_STRING_HAS_SUITABLE_NAME,
    FIELD_NUMBER_HAS_SUITABLE_NAME,
    FIELD_TIME_HAS_SUITABLE_NAME_OR_SUITABLE_ANNOTATION,

    FIELD_STRING_HAS_SUITABLE_ANNOTATION,
    FIELD_NUMBER_HAS_SUITABLE_ANNOTATION,
    INCORRECT_FIELD
}
